### ISSUE TITLE
Exercise61.cpp does not compile

### ISSUE THREAD

**Issue by rioj7** [PacktWorkshops/The-CPP-Workshop#1]
The-CPP-Workshop/blob/master/Chapter08/Exercise61/Exercise61.cpp

contains syntax errors

* `f` is not attached to the number
* missing comma in function declarations

**Comment by shashwats538** [comment]
Can I work on this?

**Comment by PacktSupport** [comment]
Hello rioj7, thank you for your patience and for highlighting the issue with the code. We have incorporated the necessary changes in the code. Let us know in case of any further issues. Thanks!
