### ISSUE TITLE
Exercise08.cpp contains a syntax error

### ISSUE THREAD

**Issue by me-tusharchandra** [PacktWorkshops/The-CPP-Workshop#4]
Encountering a syntax error 
>bool bIsRunning = true; 

should be called in main().

**Comment by me-tusharchandra** [comment]
Please assign this issue to me. #4

**Comment by PacktSupport** [comment]
Hello Tushar, you are absolutely correct! We have now made the necessary changes in the code. Let us know in case of any other issues. Thanks!
